name: build-test-deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: use node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: use node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm test
      
  deploy:
    needs: test
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: Production
      url: ${{ steps.deployment.output.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: use node.js
        uses: actions/setup-node@v3.9.1
        with: 
          node-version: '20.x'
      - name: configure github pages
        uses: actions/configure-pages@v5.0.0
        with:
          static_site_generator: next
      - run: npm install
      - run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: artifact.zip
          path: './out'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with: 
          artifact_name: artifact.zip
    
